### ISSUE TITLE
Hide prefix from exported yml

### ISSUE THREAD

**Issue by SwiftWinds** [luffy-yu/conda_env_export#1]
Often, the prefix makes it impossible to use the yml on different computers since the Anaconda installation directory may differ between computers. Can you make your CLI tool omit the prefix (or at least give an option to do so)?

Many thanks for considering my request.

**Comment by luffy-yu** [comment]
Thank you for your advice. I’ll add an option “—no-prefix” in the next version. On 04/14/2021 07:07, SwiftWinds wrote: 
Often, the prefix makes it impossible to use the yml on different computers since the Anaconda installation directory may differ between computers. Can you make your CLI tool omit the prefix (or at least give an option to do so)?
Many thanks for considering my request.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/luffy-yu/conda_env_export/issues/1",
"url": "https://github.com/luffy-yu/conda_env_export/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by luffy-yu** [comment]
Done. Please update to version 0.3.2.
